version: "3"
services:
    m-users:
      build: ./m-users
      image: ims/m-users
      ports:
          - "8081:8080"
      networks:
          - backend

    m-issues:
      build: ./m-issues
      image: ims/m-issues
      ports:
          - "8082:8080"
      networks:
          - backend

    m-comments:
      build: ./m-comments
      image: ims/m-comments
      ports:
          - "8083:8080"
      networks:
          - backend

    m-chat:
      build: ./m-chat
      image: ims/m-chat
      ports:
          - "8084:8080"
      networks:
          - backend

networks:
    backend:
